FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1903 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1903 AS build
WORKDIR /src
COPY ["DealOrNoDeal/DealOrNoDeal.csproj", "DealOrNoDeal/"]
RUN dotnet restore "DealOrNoDeal/DealOrNoDeal.csproj"
COPY . .
WORKDIR "/src/DealOrNoDeal"
RUN dotnet build "DealOrNoDeal.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DealOrNoDeal.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DealOrNoDeal.dll"]