version: 2.1

orbs:
 win: circleci/windows@2.2.0
 docker: circleci/docker@1.0.1

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run:
          command: |
            docker build -t DealOrNoDeal .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker tag boku nfs333/MyProject
            docker push nfs333/MyProject

