version: 2.1

orbs:
 docker: circleci/docker@1.0.1

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:

workflows:
  push:
    jobs:
      - build-and-push

