version: 2.1

orbs:
 docker: circleci/docker@1.0.1

jobs:
  build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: |
            docker build -f Dockerfile ..

