name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore DealOrNoDeal/DealOrNoDeal.sln
    - name: Build
      run: dotnet build DealOrNoDeal/DealOrNoDeal.sln --no-restore
    - name: Test
      run: dotnet test DealOrNoDeal/DealOrNoDeal.sln --no-build --verbosity normal
